### ISSUE TITLE
import Database Error

### ISSUE THREAD

**Issue by bapcai02** [MUSTAFA-Hamzawy/Portfolio-Website#12]
I have imported your sql file, but when running composer install it fails, can you check your sql dump file?

![image](https://user-images.githubusercontent.com/44980082/219706938-10a9125f-486d-4c14-b1c2-6384c7cb0835.png)

![image](https://user-images.githubusercontent.com/44980082/219707001-e578f3bc-e103-4c49-9df2-54d0afaf8550.png)

I fixed it by recreating 2 tables "blog_posts_view`" and "portfolio_projects_view"

**Comment by MUSTAFA-Hamzawy** [comment]
I have already added these two views (blog_posts_view, portfolio_projects_view) in the database file, are you sure you cloned the repo from the main branch ?

**Comment by bapcai02** [comment]
I cloned the code from branch "main" and imported the sql file and got the above error, do you have a developing branch, for example develop branch?****

**Comment by bapcai02** [comment]
Can you check the sql file again?

**Comment by MUSTAFA-Hamzawy** [comment]
> I cloned the code from branch "main" and imported the sql file and got the above error, do you have a developing branch, for example develop branch?****

Did you created .env file ?

**Comment by MUSTAFA-Hamzawy** [comment]
> Can you check the sql file again?

nothing with it, when i import it in phpmyadmin there is no error.
you ca follow the installation steps in the readme again

**Comment by MUSTAFA-Hamzawy** [comment]
Well, I figured the problem and fixed it.
You can try again now.
